import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import Providers from "@/components/ui/Providers";
import { options } from '@/app/api/auth/[...nextauth]/options';
import { getServerSession } from "next-auth";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(options) // this is for performance 


  return (
    <html lang="en">
      <body
        className={`  antia liased`}
      >
        <Providers session={session}>
          <nav>
            <Navbar />
            
          </nav>
          <div
            className='sm:pt-16 bg-gray-800  '
          >
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
