import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import Providers from "@/components/ui/Providers";
import { options } from '@/app/api/auth/[...nextauth]/options';
import { getServerSession } from "next-auth";
import ReduxProvider from "@/lib/store/ReduxProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(options) // this is for performance 


  return (
    <html lang="en">
      <body
        className={`  antia liased`}
      >
        <ReduxProvider>
          <Providers session={session}>
            <div
              className="h-screen flex flex-col "
            >
              <nav>
                <Navbar />
              </nav>

              <div
                // todo manage its height
                className=' flex-1'
              >
                {children}
                <div id="portal-root" />
              </div>

            </div>
          </Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
